on:
  push:
    branches:
      - develop

name: Deploy and Slack Notification
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: docker://rtcamp/action-deploy-wordpress:master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        WP_VERSION: 5.5
        # MU_PLUGINS_URL: vip
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
